title: less is more
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Matthew Bao
avatar: /logo2.png
email: matthewbao24@outlook.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
#  username: ngzhio
#  card: summary
logo: logo2.png
social:
  name: Matthew Bao
  links:
    - https://github.com/matthewBao24
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
